### ISSUE TITLE
Array 'items' gets required=true assigned

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#12]
Not sure if it makes sense. Relative to what `items` are required?
PS. Canonical form

```
Cat:
  properties:
    pawsNames:
      type: array
      items: string
```

```
{
  "properties": {
    "pawsNames": {
      "type": "array",
      "items": {
        "type": "string",
        "required": true
      },
      "required": true
    }
  },
  "additionalProperties": true,
  "type": "object",
  "required": true
}
```
