### ISSUE TITLE
Properties ending with "?" aren't made optional anymore

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#15]
Getting canonical form type with property ending with "?" doesn't make it `required: false` anymore. Iif I recall correctly it used to work before recent updates.

```
Cat:
  type: object
  properties:
    name?:
      type: string
```

```
{
  "properties": {
    "name?": {
      "type": "string",
      "required": true
    }
  },
  "additionalProperties": true,
  "type": "object",
  "required": true
}
```
