### ISSUE TITLE
'xml' node is lost on inheritance 

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#16]
I'm talking about this thing https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#xml-serialization-of-type-instances

When supertype defines `xml` node, subtype doesn't have it when getting canonical form.
If defined directly on subtype it stays.

Getting canonical form of `Cat` gives:

```
Animal:
  type: string
  maxLength: 42
  xml:
    attribute: false
    wrapped: true
    name: cat
    prefix: animal
Cat:
  type: Animal
```

```
{
  "type": "string",
  "maxLength": 42,
  "required": true
}
```
