### ISSUE TITLE
Canonical form of type 'file' is missing 'fileTypes'

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#17]
`fileTypes` is missing is canonical form of following type.

```
Cat:
  properties:
    photo:
      type: file
      fileTypes: ['image/jpeg', 'image/png']
      minLength: 1
      maxLength: 307200
```

```
{
  "properties": {
    "photo": {
      "type": "file",
      "minLength": 1,
      "maxLength": 307200,
      "required": true
    }
  },
  "additionalProperties": true,
  "type": "object",
  "required": true
}
```

It is also missing when type subclasses type "file":

```
Cat:
  type: file
  fileTypes: ['image/jpeg', 'image/png']
  minLength: 1
  maxLength: 307200
```

```
{
  "type": "file",
  "minLength": 1,
  "maxLength": 307200,
  "required": true
}
```
