### ISSUE TITLE
Using union in type's `type` gives weird output

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#24]
Getting canonical form of `Device` gives following output with a bunch of `null`s

```
Phone:
  type: object
  properties:
    manufacturer:
      type: string
    numberOfSIMCards:
      type: number
    kind: string
Notebook:
  type: object
  properties:
    manufacturer:
      type: string
    numberOfUSBPorts:
      type: number
    kind: string
Device:
  type: Phone | Notebook
```

```
{
  "discriminatorValue": null,
  "enum": null,
  "additionalProperties": null,
  "format": null,
  "multipleOf": null,
  "maxProperties": null,
  "uniqueItems": null,
  "anyOf": [
    {
      "properties": {
        "manufacturer": {
          "type": "string",
          "required": true
        },
        "numberOfSIMCards": {
          "type": "number",
          "required": true
        },
        "kind": {
          "type": "string",
          "required": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    {
      "properties": {
        "manufacturer": {
          "type": "string",
          "required": true
        },
        "numberOfUSBPorts": {
          "type": "number",
          "required": true
        },
        "kind": {
          "type": "string",
          "required": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    }
  ],
  "default": null,
  "maximum": null,
  "type": "union",
  "minLength": null,
  "title": null,
  "minProperties": null,
  "examples": null,
  "fileTypes": null,
  "minimum": null,
  "minItems": null,
  "maxLength": null,
  "example": null,
  "xml": null,
  "required": null,
  "discriminator": null,
  "maxItems": null,
  "pattern": null
}
```
