### ISSUE TITLE
description, displayName, facets are lost on property

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#26]
When getting canonical form of RAML type, `description`, `displayName`, `facets` and defined facet value of property are lost. 

```
Cat:
  type: object
  properties:
    name:
      description: Cat name
      displayName: Cat
      type: string
      facets:
        amazing: boolean
      amazing: true
```

```
{
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "additionalProperties": true,
  "type": "object"
}
```
