### ISSUE TITLE
Expanded script loses restrictions of optional properties

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#3]
Below are a type and result of converting it to expanded form. As you can see, `minLength` restriction is lost.

```
Person:
  properties:
    bio:
      type: string?
      minLength: 1
```

```
{
  "properties": {
    "bio": {
      "type": "union",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "nil"
        }
      ]
    }
  },
  "additionalProperties": true,
  "type": "object",
  "required": true
}
```
