### ISSUE TITLE
Using multiple inheritance in root gives much prettier output

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#31]
This isn't the issues really, rather NOT using multiple inheritance in root gives a lot bigger and complicated output :)
This is just a thing to consider. Maybe there's something going on wrong in scripts.

E.g. if here is canonical form of type without multiple inheritance in root. As you can see, it places `anyOf` in root and adds multiple copies with a whole object just with a different values for `age` field type.

```
types:
  CatWithCity:
    properties:
      city: string
  Cat:
    type: CatWithCity
    properties:
      age: string | number
```

```
{
  "additionalProperties": true,
  "type": "union",
  "anyOf": [
    {
      "additionalProperties": true,
      "type": "object",
      "properties": {
        "age": {
          "type": "string",
          "required": true
        },
        "city": {
          "type": "string",
          "required": true
        }
      }
    },
    {
      "additionalProperties": true,
      "type": "object",
      "properties": {
        "age": {
          "type": "number",
          "required": true
        },
        "city": {
          "type": "string",
          "required": true
        }
      }
    }
  ]
}
```

Now if we add multiple inheritance, the output becomes much more pretty branching only where it's really needed and not in the root.

```
types:
  CatWithCity:
    properties:
      city: string

  CatWithAddress:
    properties:
      address: string

  Cat:
    type: [CatWithCity, CatWithAddress]
    properties:
      age: string | number
```

```
{
  "additionalProperties": true,
  "type": "object",
  "properties": {
    "address": {
      "type": "string",
      "required": true
    },
    "city": {
      "type": "string",
      "required": true
    },
    "age": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ],
      "type": "union",
      "required": true
    }
  }
}
```
