### ISSUE TITLE
Multiple inheritance + custom type bug

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#32]
Note that getting canonical form if type `Cat` produces JSON with nested `type.type` for property `name`.

```
#%RAML 1.0 Library

types:
  CatName:
    type: string

  CatWithCity:
    type: object

  CatWithAddress:
    type: object

  Cat:
    type: [CatWithAddress, CatWithCity]
    properties:
      name:
        type: CatName
```

```
{
  "additionalProperties": true,
  "type": "object",
  "properties": {
    "name": {
      "type": {
        "type": "string"
      },
      "required": true
    }
  }
}
```
