### ISSUE TITLE
Subtype required=true doesn't override supertype required=false

### ISSUE THREAD

**Issue by postatum** [raml-org/datatype-expansion#4]
Subtype property with `required=true` doesn't override supertype's property with `required=false`. Isn't `required=true` more strict than `required=false`?

Suggestion: [here](https://github.com/raml-org/raml-parser-toolbelt/blob/master/tools/datatype-expansion/src/clj/datatype_expansion/canonical_form.cljc#L30) replace `(and super sub)` with `(or super sub)`.

Type to test and output of canonical script:

```
Person:
  properties:
    name:
      type: string
      required: true
  type:
    type: object
    properties:
      name:
        type: string
        required: false
```

```
{
  "additionalProperties": true,
  "type": "object",
  "required": true,
  "properties": {
    "name": {
      "type": "string",
      "required": false
    }
  }
}
```
