### ISSUE TITLE
Type of a `body` object is sometimes not processed by the library.

### ISSUE THREAD

**Issue by jarrodek** [raml-org/datatype-expansion#46]
Source RAML: https://github.com/raml-org/raml-examples/blob/master/others/alainn-mobile-shopping/api.raml

This is very rare but I've noticed that in this case the `type` is not handled properly.

For the POST `/mobile-tokens/{mobileType}` which is defined as:
```
/mobile-tokens/{mobileType}:
  uriParameters:
    mobileType:
      type: string
      enum: [ios, android]
  post:
    body:
      type:
        properties:
          token: string
        example:
          token: afdasfas23lkesf
```
the output object is:
```
{
body: [
  {
    "name": "application/json",
    "displayName": "application/json",
    "required": true,
    "type": {
      "name": "type",
      "displayName": "type",
      "type": "object",
      "required": true,
      "properties": [
        {
          "name": "token",
          "displayName": "token",
          "type": "string",
          "required": true,
          "key": "token"
        }
      ],
      "examples": [
        "{\n  \"token\": \"afdasfas23lkesf\"\n}"
      ]
    },
    "key": "application/json"
  }
]
}
```
The problem is that the `type` property should equals `object` and the type properties should have been promoted to parent object.
