### ISSUE TITLE
datatype-expansion does not expand `type: <<resourcePathName>>`

### ISSUE THREAD

**Issue by jstoiko** [raml-org/datatype-expansion#53]
It would be nice if datatype-expansion supported [`<<resourcePathName>>`](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#resource-type-and-trait-parameters) as a `type` value to be expanded.

NOTE: this was originally reported in https://github.com/mulesoft/osprey/issues/134 

E.g. 
```
#%RAML 1.0
title: test
mediaType: application/json

types:
  test:
    properties:
      test_value: string

resourceTypes:
  testType:
    post:
      body:
        type:  <<resourcePathName>>

/test:
  type: testType

```
